# Generated by Django 5.1.1 on 2024-10-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launchsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_Detail',
        ),
    ]
